<?php
$page_title='Books'; require __DIR__.'/includes/header.php';
$msg=''; $error='';
if($_SERVER['REQUEST_METHOD']==='POST'){
 $action=$_POST['action']??'';
 try{
  if($action==='add'){
   $stmt=$pdo->prepare('INSERT INTO books(title,author,isbn,category_id,quantity,available_quantity) VALUES(?,?,?,?,?,?)'); $q=max(1,(int)$_POST['quantity']); $stmt->execute([trim($_POST['title']),trim($_POST['author']),trim($_POST['isbn']),($_POST['category_id']?:null),$q,$q]); $msg='Book added successfully.';
  } elseif($action==='delete'){ $stmt=$pdo->prepare('DELETE FROM books WHERE id=?'); $stmt->execute([(int)$_POST['id']]); $msg='Book deleted.'; }
 }catch(PDOException $e){$error='Could not save book. ISBN may already exist or the book has active transactions.';}
}
$categories=$pdo->query('SELECT * FROM categories ORDER BY name')->fetchAll();
$q=trim($_GET['q']??''); $stmt=$pdo->prepare('SELECT b.*,c.name category FROM books b LEFT JOIN categories c ON c.id=b.category_id WHERE b.title LIKE ? OR b.author LIKE ? OR b.isbn LIKE ? ORDER BY b.id DESC'); $like="%$q%"; $stmt->execute([$like,$like,$like]); $books=$stmt->fetchAll();
?><section class="panel"><div class="panel-head"><h2>Book Catalogue</h2><button class="btn primary" onclick="openModal('bookModal')">+ Add Book</button></div><?php if($msg): ?><div class="alert success"><?=e($msg)?></div><?php endif; ?><?php if($error): ?><div class="alert error"><?=e($error)?></div><?php endif; ?><form class="search" method="get"><input name="q" value="<?=e($q)?>" placeholder="Search title, author or ISBN"><button class="btn">Search</button></form><div class="table-wrap"><table><thead><tr><th>Title</th><th>Author</th><th>ISBN</th><th>Category</th><th>Copies</th><th>Available</th><th>Action</th></tr></thead><tbody><?php foreach($books as $b): ?><tr><td><?=e($b['title'])?></td><td><?=e($b['author'])?></td><td><?=e($b['isbn'])?></td><td><?=e($b['category']??'—')?></td><td><?=$b['quantity']?></td><td><?=$b['available_quantity']?></td><td><form method="post" onsubmit="return confirm('Delete this book?')"><input type="hidden" name="action" value="delete"><input type="hidden" name="id" value="<?=$b['id']?>"><button class="btn danger">Delete</button></form></td></tr><?php endforeach; ?></tbody></table></div></section><div id="bookModal" class="modal"><div class="modal-box"><button class="close" onclick="closeModal('bookModal')">×</button><h2>Add Book</h2><form method="post"><input type="hidden" name="action" value="add"><label>Title<input name="title" required></label><label>Author<input name="author" required></label><label>ISBN<input name="isbn" required></label><label>Category<select name="category_id"><option value="">None</option><?php foreach($categories as $c): ?><option value="<?=$c['id']?>"><?=e($c['name'])?></option><?php endforeach; ?></select></label><label>Quantity<input type="number" name="quantity" min="1" value="1" required></label><button class="btn primary full">Add Book</button></form></div></div><?php require __DIR__.'/includes/footer.php'; ?>
