<?php
$page_title='Transactions'; require __DIR__.'/includes/header.php'; $msg='';$error='';
if($_SERVER['REQUEST_METHOD']==='POST'){
 try{
  if(($_POST['action']??'')==='issue'){
   $pdo->beginTransaction(); $s=$pdo->prepare('SELECT available_quantity FROM books WHERE id=? FOR UPDATE');$s->execute([(int)$_POST['book_id']]);$book=$s->fetch();
   if(!$book || $book['available_quantity']<1) throw new Exception('No available copy.');
   $s=$pdo->prepare('INSERT INTO transactions(book_id,member_id,issued_at,due_date) VALUES(?,?,CURDATE(),DATE_ADD(CURDATE(),INTERVAL 14 DAY))');$s->execute([(int)$_POST['book_id'],(int)$_POST['member_id']]);
   $pdo->prepare('UPDATE books SET available_quantity=available_quantity-1 WHERE id=?')->execute([(int)$_POST['book_id']]); $pdo->commit();$msg='Book issued for 14 days.';
  } elseif($_POST['action']==='return'){
   $pdo->beginTransaction();$s=$pdo->prepare('SELECT * FROM transactions WHERE id=? AND status=\'issued\' FOR UPDATE');$s->execute([(int)$_POST['id']]);$t=$s->fetch();if(!$t) throw new Exception('Transaction not found.');
   $fine=max(0,(int)((strtotime(date('Y-m-d'))-strtotime($t['due_date']))/86400))*10; $pdo->prepare("UPDATE transactions SET returned_at=CURDATE(),fine=?,status='returned' WHERE id=?")->execute([$fine,$t['id']]);$pdo->prepare('UPDATE books SET available_quantity=available_quantity+1 WHERE id=?')->execute([$t['book_id']]);$pdo->commit();$msg='Book returned. Fine: ₹'.number_format($fine,2);
  }
 }catch(Throwable $e){if($pdo->inTransaction())$pdo->rollBack();$error=$e->getMessage();}
}
$books=$pdo->query('SELECT id,title,available_quantity FROM books WHERE available_quantity>0 ORDER BY title')->fetchAll();$members=$pdo->query('SELECT id,member_code,name FROM members ORDER BY name')->fetchAll();$rows=$pdo->query("SELECT t.*,b.title,m.member_code,m.name FROM transactions t JOIN books b ON b.id=t.book_id JOIN members m ON m.id=t.member_id ORDER BY t.id DESC")->fetchAll();
?><section class="grid-two"><div class="panel"><h2>Issue a Book</h2><?php if($msg): ?><div class="alert success"><?=e($msg)?></div><?php endif;?><?php if($error): ?><div class="alert error"><?=e($error)?></div><?php endif;?><form method="post"><input type="hidden" name="action" value="issue"><label>Book<select name="book_id" required><option value="">Select book</option><?php foreach($books as $b): ?><option value="<?=$b['id']?>"><?=e($b['title'])?> (<?=$b['available_quantity']?> available)</option><?php endforeach;?></select></label><label>Member<select name="member_id" required><option value="">Select member</option><?php foreach($members as $m): ?><option value="<?=$m['id']?>"><?=e($m['member_code'].' - '.$m['name'])?></option><?php endforeach;?></select></label><button class="btn primary full">Issue Book</button></form></div><div class="panel"><h2>Policy</h2><p>Loan period: <b>14 days</b>.</p><p>Late fine: <b>₹10 per day</b>.</p><p>Returning a book immediately increases its available quantity.</p></div></section><section class="panel"><div class="panel-head"><h2>Transaction History</h2></div><div class="table-wrap"><table><thead><tr><th>Book</th><th>Member</th><th>Issued</th><th>Due</th><th>Returned</th><th>Fine</th><th>Status</th><th>Action</th></tr></thead><tbody><?php foreach($rows as $r): ?><tr><td><?=e($r['title'])?></td><td><?=e($r['member_code'])?> - <?=e($r['name'])?></td><td><?=$r['issued_at']?></td><td><?=$r['due_date']?></td><td><?=$r['returned_at']??'—'?></td><td>₹<?=number_format((float)$r['fine'],2)?></td><td><span class="badge <?=$r['status']?>"><?=ucfirst($r['status'])?></span></td><td><?php if($r['status']==='issued'): ?><form method="post"><input type="hidden" name="action" value="return"><input type="hidden" name="id" value="<?=$r['id']?>"><button class="btn secondary">Return</button></form><?php else: ?>—<?php endif;?></td></tr><?php endforeach;?></tbody></table></div></section><?php require __DIR__.'/includes/footer.php'; ?>
